name: Deploy HKJC Betslip Web

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 0'
    - cron: '15 4 * * 0'
    - cron: '30 9 * * 3'
    - cron: '45 10 * * 3'
    - cron: '0 6 * * 5'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install numpy pandas requests lightgbm joblib lxml html5lib scikit-learn

      - name: Auto Detect Race Day and Generate Mobile Web
        run: |
          python generate_html.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
